version: '3'
services:
  ####################################################################################################
  # The nginx Server
  ####################################################################################################
  nginx:
    build:
      context: ./
      dockerfile: ./docker-dev/nginx/nginx.dockerfile
    working_dir: /var/www
    volumes:
      - ./docker-dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./source/public:/var/www/public
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - php
  ####################################################################################################
  # App
  ####################################################################################################
  php:
    build:
      context: ./
      dockerfile: ./docker-dev/php.dockerfile
    working_dir: /var/www
    links:
      - mysql
      # - redis
    volumes:
      - ./source/:/var/www
  ####################################################################################################
  # MySQL
  ####################################################################################################
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    expose:
      - 3306
    volumes:
      - mysqlData:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: laravel
  ####################################################################################################
  # Node Assets Compiler
  ####################################################################################################
  node:
    build:
      context: ./
      dockerfile: ./docker-dev/node.dockerfile
    volumes:
      - ./source:/home/node/app
  ####################################################################################################
  # Phpmyadmin
  ####################################################################################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_HOSTS=mysql
      - PMA_PORT=3306
      - PMA_USER=laravel
      - PMA_PASSWORD=root
    ports:
      - '8081:80'
    links:
      - mysql
  ####################################################################################################
  # Redis
  ####################################################################################################
  # redis:
  #   image: redis:5-stretch
  #   ports:
  #       - "6379:6379"
  #   expose:
  #       - 6379
  #   volumes:
  #       - redisData:/data
  ####################################################################################################
  # Elasticsearch
  ####################################################################################################
  # elasticsearch:
  #   image: elasticsearch:5
  #   ports:
  #     - '9200:9200'
  #     - '9300:9300'
  #   expose:
  #     - 9200
  #     - 9300
  #   volumes:
  #     - elasticsearchData:/usr/share/elasticsearch/data
  #   environment:
  #     - cluster.name=laravel-cluster
  #     - bootstrap.memory_lock=true
  #     - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
  ####################################################################################################
  # Mongo
  ####################################################################################################
  # mongodb:
  #   image: mongo:4-xenial
  #   container_name: "mongodb"
  #   ports:
  #       - 27017:27017
volumes:
  mysqlData:
  redisData:
  elasticsearchData:

