version: '3'
services:
  ####################################################################################################
  # The Web Server
  ####################################################################################################
  web:
    build:
      context: ./
      dockerfile: ./docker/web.dockerfile
    working_dir: /var/www
    volumes:
      - ./docker/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./source/public:/var/www/public
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
  ####################################################################################################
  # App
  ####################################################################################################
  app:
    build:
      context: ./
      dockerfile: ./docker/app.dockerfile
    working_dir: /var/www
    links:
      - mysql
      # - redis
    volumes:
      - ./source/:/var/www
  ####################################################################################################
  # Redis
  ####################################################################################################
  # redis:
  #   image: redis:latest
  #   ports:
  #       - "6379:6379"
  #   expose:
  #       - 6379
  #   volumes:
  #       - ./image/redis/data:/data
  ####################################################################################################
  # MySQL
  ####################################################################################################
  mysql:
    image: mysql:5.7
    ports:
        - "3306:3306"
    expose:
        - 3306
    volumes:
        - ./image/mysql/data/:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: laravel
        MYSQL_PASSWORD: root
        MYSQL_DATABASE: root
  ####################################################################################################
  # Node Assets Compiler
  ####################################################################################################
  node:
    build:
      context: ./
      dockerfile: ./docker/node.dockerfile
    volumes:
      - ./source:/home/node/app

