version: '3'
services:
  ####################################################################################################
  # The Web Server
  ####################################################################################################
  web:
    build:
      context: ./
      dockerfile: ./docker-dev/web.dockerfile
    working_dir: /var/www
    volumes:
      - ./docker-dev/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./source/public:/var/www/public
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - app
  ####################################################################################################
  # App
  ####################################################################################################
  app:
    build:
      context: ./
      dockerfile: ./docker-dev/app.dockerfile
    working_dir: /var/www
    links:
      - mysql
      # - redis
    volumes:
      - ./source/:/var/www
  ####################################################################################################
  # MySQL
  ####################################################################################################
  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    expose:
      - 3306
    volumes:
      - ./image/mysql/data/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: root
  ####################################################################################################
  # Node Assets Compiler
  ####################################################################################################
  node:
    build:
      context: ./
      dockerfile: ./docker-dev/node.dockerfile
    volumes:
      - ./source:/home/node/app
  ####################################################################################################
  # Phpmyadmin
  ####################################################################################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '8081:80'
    links:
      - mysql
  ####################################################################################################
  # Redis
  ####################################################################################################
  # redis:
  #   image: redis:latest
  #   ports:
  #       - "6379:6379"
  #   expose:
  #       - 6379
  #   volumes:
  #       - ./image/redis/data:/data
  ####################################################################################################
  # Elasticsearch
  ####################################################################################################
  # elasticsearch:
  #   image: elasticsearch:latest
  #   ports:
  #     - '9200:9200'
  #     - '9300:9300'
  #   expose:
  #     - 9200
  #     - 9300
  #   volumes:
  #     - ./image/elasticsearch:/usr/share/elasticsearch/data
  #   environment:
  #     - cluster.name=laravel-cluster
  #     - bootstrap.memory_lock=true
  #     - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
  ####################################################################################################
  # Mongo
  ####################################################################################################
  # mongodb:
  #   image: mongo:latest
  #   container_name: "mongodb"
  #   ports:
  #       - 27017:27017

